# Generated by Django 4.1.7 on 2023-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadimage",
            name="name",
            field=models.CharField(default="image", max_length=255),
        ),
    ]
