# Generated by Django 4.1.7 on 2023-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SR", "0002_uploadimage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
