# Generated by Django 4.1.7 on 2023-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SR", "0003_alter_uploadimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Video", max_length=255)),
                ("Video", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
