# Generated by Django 4.1.7 on 2023-05-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SR", "0004_uploadvideo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadvideo",
            old_name="Video",
            new_name="video",
        ),
    ]
